// tax-filer-frontend/src/components/HomePage.js
import React from 'react';
import { Link } from 'react-router-dom';
import '../HomePage.css';
import { FiCheckSquare, FiCpu, FiSmartphone } from 'react-icons/fi';

const HomePage = () => {
  return (
    <div className="home-page">
      <section className="hero-section animate__animated animate__fadeIn">
        <h1 className="animate__animated animate__fadeInDown">
          Welcome to the Intelligent Tax Filer
        </h1>
        <p className="subtitle animate__animated animate__fadeInUp animate__delay-1s">
          Simplify your tax preparation process with AI-powered insights. Get
          preliminary advice based on your financial information quickly and
          easily.
        </p>
        <Link
          to="/tax-form"
          className="button-link animate__animated animate__pulse animate__delay-2s animate__infinite"
        >
          Get Started
        </Link>
      </section>

      <section className="features-section">
        <h2 className="animate__animated animate__fadeInUp">Key Features</h2>
        <div className="features-grid">
          <div className="feature-item animate__animated animate__fadeInUp animate__delay-1s">
            {
              <FiCheckSquare
                size={40}
                style={{ marginBottom: '15px', color: '#E0007C' }}
              />
            }
            <h3>Easy-to-Use Form</h3>
            <p>Input your tax data through a simple and intuitive interface.</p>
          </div>
          <div className="feature-item animate__animated animate__fadeInUp animate__delay-2s">
            {
              <FiCpu
                size={40}
                style={{ marginBottom: '15px', color: '#E0007C' }}
              />
            }
            <h3>AI-Powered Advice</h3>
            <p>
              Receive general tax considerations generated by an advanced AI
              model.
            </p>
          </div>
          <div className="feature-item animate__animated animate__fadeInUp animate__delay-3s">
            {
              <FiSmartphone
                size={40}
                style={{ marginBottom: '15px', color: '#E0007C' }}
              />
            }
            <h3>Responsive Design</h3>
            <p>Access the application seamlessly on any device, anytime.</p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HomePage;
