name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'tax-filer-frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tax-filer-frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-test-build:
    name: Lint, Test & Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tax-filer-frontend # Set working directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Cache npm dependencies
          cache-dependency-path: tax-filer-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npm run lint

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Run tests with Jest
        run: npm test -- --coverage # Run tests and generate coverage
        env:
          CI: true

      - name: Build application
        run: npm run build
        env:
          REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL_CI || 'http://localhost:8000/api/v1' }}
          # Use GitHub variables (vars) for non-sensitive build-time configs.
          # In production, this URL should point to the deployed backend, fine for now.

      # Archive production artifacts
      - name: Archive production build
        if: success() && github.event_name == 'push' # Archive only on successful push
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: tax-filer-frontend/build
          if-no-files-found: error # Fail if build directory is not found

  build-docker-image:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    needs: lint-test-build # Run after successful build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only on push to main
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tax-filer-frontend
          file: ./tax-filer-frontend/Dockerfile
          push: false
          tags: |
            local/tax-filer-frontend:latest
            local/tax-filer-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: | # Pass build args to Dockerfile
            REACT_APP_API_BASE_URL=${{ vars.REACT_APP_API_BASE_URL || 'http://localhost:8000/api/v1' }}
          load: true
